server:
  port: 8300
spring:
  application:
    name: curse-server
  datasource:
    username: root
    password: 202020
    url: jdbc:mysql://112.124.31.166:3306/attendance?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
  devtools:
    restart:
      additional-exclude: curse/** #控制额外路径下的更改是否触发完整重新启动或实时重新加载。
      additional-paths: /watch #配置额外的路径去监控它是否发生了改变
      enabled: false #热部署 #是否禁用重启
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
datetime:
 zero: 06:40:00~07:25:00
 first: 08:25:00~09:00:00
 second: 09:05:00~09:50:00
 third: 10:25:00~11:10:00
 fourth: 11:15:00~12:00:00
 fifth: 14:25:00~15:10:00
 sixth: 15:15:00~16:00:00
 seventh: 16:25:00~17:10:00
 eighth: 17:15:00~18:00:00
 ninth: 19:00:00~19:45:00
 tenth: 19:50:00~20:35:00
 eleventh: 20:40:00~21:25:00
# 按照默认的名称spring.log，生成到指定路径及日志。
  # 不指定的情况下默认生成在项目根目录，按照配置生成所需的日志名称
logging:
  file:
    path: D:/sign/curse
    name: curse.log
ssh:
 ip: 112.124.31.166
 name: root
 password: teng,jiayou
 port: 22
 filePath: home